config/routes.rb
Rails.application.routes.draw do
  resources :posts
  devise_for :users
  get '/movies/:id/reviews' => 'reviews#create'
  root 'movies#index'
  resources :movies

  namespace :admin do
    resources :users do
      put :upgrade, on: :member # user_id가 아니라 id로 쓰고 싶을 때 
      put :downgrade, on: :member
    end
  end

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
      if user.admin?
        can :manage, :all
      else
        can :read, :all
      end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/movie.rb
class Movie < ActiveRecord::Base
  mount_uploader :image_url, ImageUploader
  has_many :reviews

  def avg
    total = 0
    reviews.each do |r|
      total += r.rating
    end
    if reviews.count == 0
      0
    else
      total.to_f / @movie.reviews.count
    end
  end


end

app/models/post.rb
class Post < ActiveRecord::Base
  mount_uploader :photo, PhotoUploader
  belongs_to :user
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :movie
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts
# 권한부여
def admin?
  if role == "admin" #user class 여서 role로 바로 접근 가능
    true

  else
    false
  end
end


end

app/controllers/admin/application_controller.rb
class Admin::ApplicationController < ApplicationController
  before_action :check_admin
  layout 'admin'
  private
  def check_admin
    # 지금 접속한 친구가 관리자인지 판별
    # 아닐 경우 루트페이지

    unless user_signed_in? && current_user.admin? # 두개다 맞아야 한다.
      redirect_to(root_path, alert: "관리자 계정으로 로그인하셔야 합니다.")
    end

  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::ApplicationController
  def index
    @users = User.all
  end

  def destroy
    @users = User.find(params[:id])
    @users.destroy
    redirect_to admin_users_path
  end

  def upgrade
    @user = User.find(params[:id])
    @user.update(
      role: "admin"
    )
    redirect_to admin_users_path
  end

  def downgrade
    @user = User.find(params[:id])
    @user.update(
      role: "regular"
    )
    redirect_to admin_users_path
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # 모든 서비스를 사용 전에 로그인하세요
  before_action :authenticate_user!
  
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :edit, :update, :destroy]
  # before_action :check_admin, only: [:check, :edit, :destroy]
  load_and_authorize_resource
  # GET /movies
  # GET /movies.json
  def index
    @movies = Movie.all
    # authorize! :read, Movie
  end

  # GET /movies/1
  # GET /movies/1.json
  def show

    # total = 0
    # @movie.review.each do |review|
    #   total +=




    # sum = 0
    # @sum = @sum + 특정 영화에 있는 모든 리뷰들을 돌면서 하나씩 더하기
    # (1) 특정영화에 담긴 리뷰들을 다 불러온다.
    # (2) 리뷰를 각각 돌면서 rating에 담겨 있는 점수를 sum에 더한다.
    # (3) 누적된 값을 전체 리뷰 수로 나누어준다.
    # (4) avg 에 넣어서 avg출력!
    # @sum = 0
    # @num = 0
    # Movie.find(params[:id]).reviews.each do |review|
    #   @sum += review.rating
    #   @num += 1
    #   @avg = @sum / @num
    # end
    # authorize! :read, Movie
  end

  # GET /movies/new
  def new
    @movie = Movie.new
    # authorize! :create, Movie
  end

  # GET /movies/1/edit
  def edit
    # authorize! :update, Movie
  end

  # POST /movies
  # POST /movies.json
  def create

    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
    # authorize! :create, Movie
  end

  # PATCH/PUT /movies/1
  # PATCH/PUT /movies/1.json
  def update

    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
    # authorize! :update, Movie
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: 'Movie was successfully destroyed.' }
      format.json { head :no_content }
    end
    # authorize! :destroy, Movie
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movie_params
      params.require(:movie).permit(:title, :desc, :image_url)
    end

    def check_admin
      current_user.admin?
    end


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new(
      user_id: current_user.id
    )
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content, :photo, :user_id)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    Review.create(
      movie_id: params[:id],
      rating: params[:rating],
      comment: params[:comment]
    )
    redirect_to movie_path(params[:id])

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/admin/users/index.erb
<main role="main" class="col-sm-9 ml-sm-auto col-md-10 pt-3">
<h1>유저관리</h1>
<h2>유저목록</h2>
<div class="table-responsive">
  <table class="table table-striped">
    <thead>
      <tr>
        <th>ID</th>
        <th>email</th>
        <th>role</th>
        <th>등급변경</th>
        <th>삭제</th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user|%>
        <tr>
          <td><%=user.id%></td>
          <td><%=user.email%></td>
          <td><%=user.role%></td>
          <td>
            <% if user.admin? %>
              <%=link_to "[양민으로]",  downgrade_admin_user_path(user), method: :put, data: {confirm: "정말로 유저 등급을 떨어트리시겠습니까?"}%>
            <% else %>
              <%=link_to "[관리자 승급]", upgrade_admin_user_path(user), method: :put, data: {confirm: "정말로 유저 등급을 올리시겠습니까?"}%>
            <% end %>
          </td>
          <td><%=link_to "[삭제]", admin_user_path(user),  method:"delete", data: {confirm: "정말로 삭제 하시겠습니까?"}%></td>
        <% end %>
      </tr>
    </tbody>
  </table>
</div>
</main>

app/views/layouts/_admin_header.erb
<header>
     <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
       <a class="navbar-brand" href="#">Dashboard</a>
       <button class="navbar-toggler d-lg-none" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
         <span class="navbar-toggler-icon"></span>
       </button>

       <div class="collapse navbar-collapse" id="navbarsExampleDefault">
         <ul class="navbar-nav mr-auto">
           <li class="nav-item active">
             <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
           </li>
           <li class="nav-item">
             <a class="nav-link" href="#">Settings</a>
           </li>
           <li class="nav-item">
             <a class="nav-link" href="#">Profile</a>
           </li>
           <li class="nav-item">
             <a class="nav-link" href="#">Help</a>
           </li>
         </ul>
         <form class="form-inline mt-2 mt-md-0">
           <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
           <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
         </form>
       </div>
     </nav>
   </header>

app/views/layouts/_admin_menu.erb
<nav class="col-sm-3 col-md-2 d-none d-sm-block bg-light sidebar">
   <ul class="nav nav-pills flex-column">
     <li class="nav-item">
       <a class="nav-link active" href="#">유저관리 <span class="sr-only">(current)</span></a>
     </li>
     <li class="nav-item">
       <a class="nav-link" href="#">영화관리</a>
     </li>
     <li class="nav-item">
       <a class="nav-link" href="#">게시판관리</a>
     </li>
     <li class="nav-item">
       <a class="nav-link" href="#">블로그관리</a>
     </li>
   </ul>
 </nav>

app/views/layouts/_footer.erb
<footer class="mdl-mega-footer">
  <div class="mdl-mega-footer__middle-section">

    <div class="mdl-mega-footer__drop-down-section">
      <input class="mdl-mega-footer__heading-checkbox" type="checkbox" checked>
      <h1 class="mdl-mega-footer__heading">Features</h1>
      <ul class="mdl-mega-footer__link-list">
        <li><a href="#">About</a></li>
        <li><a href="#">Terms</a></li>
        <li><a href="#">Partners</a></li>
        <li><a href="#">Updates</a></li>
      </ul>
    </div>

    <div class="mdl-mega-footer__drop-down-section">
      <input class="mdl-mega-footer__heading-checkbox" type="checkbox" checked>
      <h1 class="mdl-mega-footer__heading">Details</h1>
      <ul class="mdl-mega-footer__link-list">
        <li><a href="#">Specs</a></li>
        <li><a href="#">Tools</a></li>
        <li><a href="#">Resources</a></li>
      </ul>
    </div>

    <div class="mdl-mega-footer__drop-down-section">
      <input class="mdl-mega-footer__heading-checkbox" type="checkbox" checked>
      <h1 class="mdl-mega-footer__heading">Technology</h1>
      <ul class="mdl-mega-footer__link-list">
        <li><a href="#">How it works</a></li>
        <li><a href="#">Patterns</a></li>
        <li><a href="#">Usage</a></li>
        <li><a href="#">Products</a></li>
        <li><a href="#">Contracts</a></li>
      </ul>
    </div>

    <div class="mdl-mega-footer__drop-down-section">
      <input class="mdl-mega-footer__heading-checkbox" type="checkbox" checked>
      <h1 class="mdl-mega-footer__heading">FAQ</h1>
      <ul class="mdl-mega-footer__link-list">
        <li><a href="#">Questions</a></li>
        <li><a href="#">Answers</a></li>
        <li><a href="#">Contact us</a></li>
      </ul>
    </div>

  </div>

  <div class="mdl-mega-footer__bottom-section">
    <div class="mdl-logo">Title</div>
    <ul class="mdl-mega-footer__link-list">
      <li><a href="#">Help</a></li>
      <li><a href="#">Privacy & Terms</a></li>
    </ul>
  </div>

</footer>

app/views/layouts/_header.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">

      <%=link_to 'home', root_path, class: 'nav-item nav-link active'%>
      <% if user_signed_in? %>
        <%=link_to 'logout', destroy_user_session_path, method:"delete", class: 'nav-item nav-link active'%>
      <% else %>
        <%=link_to 'sign up', new_user_registration_path, class: 'nav-item nav-link active'%>
        <%=link_to 'login', new_user_session_path, class: 'nav-item nav-link active'%>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>왓챠 : 관리자 페이지</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
</head>
<body>
<%= render 'layouts/admin_header' %>
<% if user_signed_in? %>
<%= current_user.email%>님 환영합니다.
<% end %>

<div class="container-fluid">
  <div class="row">
  <%= render 'layouts/admin_menu'%>
  <%= yield %>
  </div>
</div>


<!-- <%=link_to 'home', root_path%>
<% if user_signed_in? %>
  <%=link_to 'logout', destroy_user_session_path, method:"delete"%><br>
  <%= current_user.email%>님 환영합니다.
<% else %>
  <%=link_to 'login', new_user_session_path%>
  <%=link_to 'sign up', new_user_registration_path%>
<% end %> -->

<!-- <p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p> -->
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>왓챠 : 영화평점서비스</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
</head>
<body>

<%= render 'layouts/header' %>


<!-- <%=link_to 'home', root_path%>
<% if user_signed_in? %>
  <%=link_to 'logout', destroy_user_session_path, method:"delete"%><br>
  <%= current_user.email%>님 환영합니다.
<% else %>
  <%=link_to 'login', new_user_session_path%>
  <%=link_to 'sign up', new_user_registration_path%>
<% end %> -->

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<%= yield %>
<!-- <%= render 'layouts/footer'%> -->

</body>
</html>

app/views/movies/_form.html.erb
<%= form_for(@movie) do |f| %>
  <% if @movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
      <% @movie.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.file_field :image_url %>
  </div>

  <div class="field">
    <%= f.label :desc %><br>
    <%= f.text_area :desc %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/movies/edit.html.erb
<h1>Editing Movie</h1>

<%= render 'form' %>

<%= link_to 'Show', @movie %> |
<%= link_to 'Back', movies_path %>

app/views/movies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Movies</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Image</th>
      <th>Desc</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @movies.each do |movie| %>
      <tr>
        <td><%= movie.title %></td>
        <td><%= image_tag movie.image_url, size:"50x50" %></td>
        <td><%= movie.desc %></td>
        <td><%= link_to 'Show', movie %></td>
        <% if current_user.admin? %>
          <td><%= link_to 'Edit', edit_movie_path(movie) %></td>
          <td><%= link_to 'Destroy', movie, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Movie', new_movie_path %>

app/views/movies/new.html.erb
<h1>New Movie</h1>

<%= render 'form' %>

<%= link_to 'Back', movies_path %>

app/views/movies/show.html.erb
<p id="notice"><%= notice %></p>


<p>
  <strong>Img:</strong>
  <%= image_tag @movie.image_url %>
</p>

<p>
  <strong>Title:</strong>
  <%= @movie.title %>
</p>

<p>
  <strong>Desc:</strong>
  <%= @movie.desc %>
</p>

<%= form_tag("/movies/#{@movie.id}/reviews", method: :get) do %>
<p>
  <strong>평점:</strong>
  <%= radio_button_tag(:rating, "1")%>
  <%= label_tag(:point_1, "1")%>
  <%= radio_button_tag(:rating, "2")%>
  <%= label_tag(:point_2, "2")%>
  <%= radio_button_tag(:rating, "3")%>
  <%= label_tag(:point_3, "3")%>
  <%= radio_button_tag(:rating, "4")%>
  <%= label_tag(:point_4, "4")%>
  <%= radio_button_tag(:rating, "5")%>
  <%= label_tag(:point_5, "5")%>
</p>
<%= text_field_tag(:comment) %>
<%= submit_tag('리뷰제출') %>
<% end %>
<!-- <%=@movie.avg%> -->
평점 평균: <%= @movie.reviews.average(:rating)%>
<% @movie.reviews.each do |review| %>

<p>
  별점수: <%= review.rating%>
</p>
<p>
  댓글: <%= review.comment%>
</p>
<% end %>

<%= link_to 'Edit', edit_movie_path(@movie) %> |
<%= link_to 'Back', movies_path %>

app/views/posts/_form.html.erb
<!-- app\views\posts\_form.html.erb -->
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.trix_editor :content %>
  </div>
  <div class="field">
    <%= f.label :photo %><br>
    <%= f.file_field :photo %>
  </div>
  <!-- <div class="field">
    <%= f.hidden_field :user_id, value: current_user.id %>
  </div> -->
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Photo</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.content.html_safe %></td>
        <td><%= post.photo %></td>
        <td><%= post.user%></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<p>
  <strong>Photo:</strong>
  <%= @post.photo %>
</p>

<p>
  <strong>User:</strong>
  <%= @post.user %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>